version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker:
          version: default
      - checkout
      - run:
          name: Authenticate to Docker Hub
          command: echo $DOCKER_TOKEN | docker login -udadlian --password-stdin
      - run: 
          name: Build Wadapi Framework base image
          command: docker build -t dadlian/wadapi:$CIRCLE_TAG -t dadlian/wadapi:latest --build-arg VERSION=$CIRCLE_TAG .
      - run:
          name: Publish Wadapi Framework base image to Docker Hub
          command: |
            docker push dadlian/wadapi:$CIRCLE_TAG
            docker push dadlian/wadapi:latest

workflows:
  publish_to_docker:
    jobs:
      - build_and_push:
          context:
            - Build Secrets 
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
